### ISSUE TITLE
AudioUnits plugin broken.

### ISSUE THREAD

**Issue by vigliensoni** [magenta/ddsp-vst#5]
I downloaded the macOS AU 1.0.0 version of the plugin and tried it on Ableton 10.1.42, Ableton 11.0.10, and Reaper 6.53.

The plugin is available to the host application but not able to load it. 

Ableton error message

<img width="479" alt="Screen Shot 2022-05-13 at 2 07 25 PM" src="https://user-images.githubusercontent.com/492229/168343679-d7065140-41b8-4c6b-8fca-008be7f65cd1.png">

In Reaper the plugin can't be activated once in a track

<img width="367" alt="Screen Shot 2022-05-13 at 2 11 47 PM" src="https://user-images.githubusercontent.com/492229/168343758-27ff4bdb-d2b9-41a9-8bd1-312e036cf744.png">

 I checked the logs of the Ableton session and got:

```
2022-05-13T14:14:49.301615: info: Au: Going to create: DDSP Effect
2022-05-13T14:14:49.311306: error: Au: Failed: DDSP Effect
2022-05-13T14:14:49.445141: info: MemoryUsage: V: 6.4 GB, R: 601.5 MB, P: 0 Bytes
2022-05-13T14:15:04.385984: info: Au: Going to create: DDSP Synth
2022-05-13T14:15:04.392137: error: Au: Failed: DDSP Synth
```

Any insights?

Thank you.

**Comment by jesseengel** [comment]
Thanks for letting us know, and sorry it's not working for you. Could you provide more information about the OS? We're collecting a table of configurations that work and don't yet work in https://github.com/magenta/ddsp-vst/blob/main/Builds.md.

We've seen it work on M1 + Intel Macs for OSX 12.3.1 but it's possible there may be some signing issues for earlier OSs.

**Comment by vigliensoni** [comment]
Yeah, I forgot to add that :)

macOS 10.15.7

Thank you!

**Comment by jacktipper** [comment]
Hello! Adding to the thread, I am running into a similar issue:
<img width="495" alt="Screen Shot 2022-05-15 at 11 17 15 PM" src="https://user-images.githubusercontent.com/74902963/168514302-6f20d910-6216-4ce8-a89e-b9f8a33ad0ae.png">

macOS 11.2.3; 2018 Intel MacBook Pro; Ableton Live Suite 11.1.1

I'm planning to update my macOS version in a few weeks, so I'll post an update if that fixes it.

Thanks again for making this! Really looking forward to getting it up and running for some creative projects.

**Comment by jesseengel** [comment]
Thanks for providing this info! Could you also add it to Builds.md so that we can keep track? Thanks!

**Comment by TimoRozendal** [comment]
I have the same thing on my Mojave machine (10.14.16 - intel)
This is what the console prints at the moment of the error:
![Screenshot 2022-05-19 at 15 25 10](https://user-images.githubusercontent.com/2157753/169304455-9fde26fb-fddb-4faa-95e0-875aed3cabea.png)

It works fine on my Monterey (12.0.1 - intel) system

**Comment by sky-supertone** [comment]
Adding as well, AU isn't passing auval 

Error Message:
validating Audio Unit DDSP Effect by Magenta:

    AU Validation Tool
    Version: 1.8.0 
    Copyright 2003-2019, Apple Inc. All Rights Reserved.
    Specify -h (-help) for command options

```
--------------------------------------------------
VALIDATING AUDIO UNIT: 'aufx' - 'Ranj' - 'Mage'
--------------------------------------------------
Manufacturer String: Magenta
AudioUnit Name: DDSP Effect
Component Version: 1.0.0 (0x10000)

* * PASS
--------------------------------------------------
TESTING OPEN TIMES:
COLD:
dyld: warning, LC_RPATH @executable_path/Frameworks in /Users/skysupertone/Library/Audio/Plug-Ins/Components/DDSPEffect.component/Contents/MacOS/DDSP being ignored in restricted program because of @executable_path (Codesign main executable with Library Validation to allow @ paths)
dyld: warning, LC_RPATH @executable_path/../Frameworks in /Users/skysupertone/Library/Audio/Plug-Ins/Components/DDSPEffect.component/Contents/MacOS/DDSP being ignored in restricted program because of @executable_path (Codesign main executable with Library Validation to allow @ paths)
dyld: warning, LC_RPATH @executable_path/Frameworks in /Users/skysupertone/Library/Audio/Plug-Ins/Components/DDSPEffect.component/Contents/MacOS/DDSP being ignored in restricted program because of @executable_path (Codesign main executable with Library Validation to allow @ paths)
dyld: warning, LC_RPATH @executable_path/../Frameworks in /Users/skysupertone/Library/Audio/Plug-Ins/Components/DDSPEffect.component/Contents/MacOS/DDSP being ignored in restricted program because of @executable_path (Codesign main executable with Library Validation to allow @ paths)
FATAL ERROR: OpenAComponent: result: -1,0xFFFFFFFF


validation result: couldn’t be opened
```

macOS 11.6 M1 Macbook Pro 2020
Logic Pro Version 10.7.2 running on Rosetta

**Comment by MrSkills** [comment]
Same issue here. The website describes it as a VST plugin, but when you download it, it's actually AU. But then the AU cannot be loaded in Logic. The validation tool gives the following output:

`validating Audio Unit DDSP Effect by Magenta:

    AU Validation Tool
    Version: 1.8.0 
    Copyright 2003-2019, Apple Inc. All Rights Reserved.
    Specify -h (-help) for command options

--------------------------------------------------
VALIDATING AUDIO UNIT: 'aufx' - 'Ranj' - 'Mage'
--------------------------------------------------
Manufacturer String: Magenta
AudioUnit Name: DDSP Effect
Component Version: 1.0.0 (0x10000)

* * PASS
--------------------------------------------------
TESTING OPEN TIMES:
COLD:
dyld: warning, LC_RPATH @executable_path/Frameworks in /Library/Audio/Plug-Ins/Components/DDSPEffect.component/Contents/MacOS/DDSP being ignored in restricted program because of @executable_path (Codesign main executable with Library Validation to allow @ paths)
dyld: warning, LC_RPATH @executable_path/../Frameworks in /Library/Audio/Plug-Ins/Components/DDSPEffect.component/Contents/MacOS/DDSP being ignored in restricted program because of @executable_path (Codesign main executable with Library Validation to allow @ paths)
dyld: warning, LC_RPATH @executable_path/Frameworks in /Library/Audio/Plug-Ins/Components/DDSPEffect.component/Contents/MacOS/DDSP being ignored in restricted program because of @executable_path (Codesign main executable with Library Validation to allow @ paths)
dyld: warning, LC_RPATH @executable_path/../Frameworks in /Library/Audio/Plug-Ins/Components/DDSPEffect.component/Contents/MacOS/DDSP being ignored in restricted program because of @executable_path (Codesign main executable with Library Validation to allow @ paths)
FATAL ERROR: OpenAComponent: result: -1,0xFFFFFFFF


validation result: couldn’t be opened
`

macOS 11.6.6 (Intel), Logic Pro 10.7.4

**Comment by jesseengel** [comment]
Hi, we just released a new version that should work with older versions of macOS (https://g.co/magenta/ddsp-vst-mac) can you try it out and see if it works for you?

Also, sorry for the confusion, VST version is on it's way :)

**Comment by MrSkills** [comment]
Yes it works for me now!

**Comment by vigliensoni** [comment]
This is also working in my setup. Thanks @jesseengel.

**Comment by jesseengel** [comment]
Great, glad it works!
